# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_MH_covariates <- function(y, category, K_per_category, prior_means, maxK, n_iter = 10000L, burnin = 2000L, proposal_sd = 0.15, alpha0 = 3.0, beta0 = 2.0, alpha_dirichlet = 5.0, seed = 123L, adaptive = TRUE) {
    .Call(`_MultiModalR_run_MH_covariates`, y, category, K_per_category, prior_means, maxK, n_iter, burnin, proposal_sd, alpha0, beta0, alpha_dirichlet, seed, adaptive)
}

MM_MH_cpp <- function(y, prior_means, n_iter = 1000L, burnin = 500L, proposal_sd = 0.15, seed = 123L) {
    .Call(`_MultiModalR_MM_MH_cpp`, y, prior_means, n_iter, burnin, proposal_sd, seed)
}

MM_MH_dirichlet_cpp <- function(y, prior_means, n_iter = 5000L, burnin = 2000L, proposal_sd = 0.15, dirichlet_alpha = 2.0, seed = 123L) {
    .Call(`_MultiModalR_MM_MH_dirichlet_cpp`, y, prior_means, n_iter, burnin, proposal_sd, dirichlet_alpha, seed)
}

