# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MM_MH_cpp <- function(y, prior_means, n_iter = 500L, burnin = 250L, proposal_sd = 0.15, seed = 123L) {
    .Call(`_MultiModalR_MM_MH_cpp`, y, prior_means, n_iter, burnin, proposal_sd, seed)
}

